### ISSUE TITLE
Output issue

### ISSUE THREAD

**Issue by Szransh** [ihdia/seamformer#2]
Hi, I used seamformer for the inference using a sample image with the Indiscape model, there is some issue with the output. Can you tell me the reason for the same?

![Screenshot 2023-10-04 at 11 06 56 PM](https://github.com/ihdia/seamformer/assets/88891963/036165e4-dac3-40ba-bd41-81856ea9c530)
Using bks model give this error and does not generate output.

No contours in the raw image!
Image :test.jpg Error :OpenCV(4.5.5) /io/opencv/modules/imgproc/src/convhull.cpp:143: error: (-215:Assertion failed) total >= 0 && (depth == CV_32F || depth == CV_32S) in function 'convexHull'

**Comment by hwaseem04** [comment]
Can you please provide the image as a link

**Comment by Szransh** [comment]
https://www.lib.uchicago.edu/media/images/glimpses__jain_manuscript.original.jpg

**Comment by dhirendracode** [comment]
same error.
Image is as follows,
![Untitled](https://github.com/ihdia/seamformer/assets/80610919/12e1d8e3-52a5-4953-95e8-339ed9cad7ed)

**Comment by hwaseem04** [comment]
Apologize for the delayed reply;
The dimension of the above image that you shared is close to (400, 1000). In general, we have observed that the model performs well when the height is not too low. You can upscale the height of the image to 1200 (worked well in general for any dataset), by maintaining the aspect ratio. You can refer this code - [Stack Overflow](https://stackoverflow.com/questions/44650888/resize-an-image-without-distortion-opencv). 
The minor distortion while upscaling doesn't impact the model performance.

![vis_glimpses_Jain_manuscript_upscaled](https://github.com/ihdia/seamformer/assets/85298297/f3dd09a7-cdfc-4f28-a06c-8ecca81cd786)
I got the above result with I2.pt (since the above image you shared belongs to Jain category which comes under I2). You also need to change the rectangularKernel parameter when it comes to I2 images. The parameter provided currently in the repo is for BKS dataset. 

```
scribbles = postProcess(scribbleMap,binaryMap,binaryThreshold=40,rectangularKernel=50)
```

This is one such very few hard image example due to the presence of illustrations. We are working towards a more robust version of the current setup that is independent of dimension, illustrations etc.

For the other question, the reason you got the error while using BKS.pt is because when you use it for I2 (say Jain) images, the thick blobs map wouldn't be properly generated. The Model fails to recognize any predicted scribble hence the error as `No contours`.

**Comment by hwaseem04** [comment]
> same error. Image is as follows, ![Untitled](https://user-images.githubusercontent.com/80610919/279678425-12e1d8e3-52a5-4953-95e8-339ed9cad7ed.jpeg)

Hi, could you check the dimension of the original image and try upscaling it like I mentioned above along with I2.pt weight.
Thank you.

**Comment by dhirendracode** [comment]
Sure, I will check the test results and will let you know

**Comment by dhirendracode** [comment]
Hi @hwaseem04 Got the results.
I think we should put the height=around 40% of width of image and of course using I2 weights.

Will share the results soon.
Thank you
